#ifndef __CLOVA_CONTEXT__
#define __CLOVA_CONTEXT__

#define CLOVA_HEADER_CLOVA_NAMESPACE "Clova"
#define CLOVA_HEADER_LOCATION_NAME "Location"
#define CLOVA_HEADER_SAVED_PLACE_NAME "SavedPlace"
#define CLOVA_HEADER_FREETALKSTATE "FreetalkState"
#define CLOVA_HEADER_ASSISTANTSTATE "Assistant"

#define CLOVA_PAYLOAD_FOREGROUND "foreground"
#define CLOVA_PAYLOAD_REPROMPT "reprompt"

#define CLOVA_HEADER_DEVICE_NAMESPACE "Device"
#define CLOVA_HEADER_DEVICE_STATE_NAME "DeviceState"
#define CLOVA_HEADER_DEVICE_DISPLAY_NAME "Display"

#define CLOVA_HEADER_SPEECHSYNTHESIZER_NAMESPACE "SpeechSynthesizer"
#define CLOVA_HEADER_SPEECH_STATE_NAME "SpeechState"

#define CLOVA_PAYLOAD_LATITUDE_NAME "latitude"
#define CLOVA_PAYLOAD_LONGITUDE_NAME "longitude"
#define CLOVA_PAYLOAD_REFRESHEDAT_NAME "refreshedAt"
#define CLOVA_PAYLOAD_NAME_NAME "name"

#define CLOVA_PAYLOAD_SIZE_NAME "size"
#define CLOVA_PAYLOAD_SIZE_VALUE_CUSTOM "custom"

#define CLOVA_PAYLOAD_PLACES_NAME "places"

#define CLOVA_PAYLOAD_SPEECH_TOKEN_NAME "token"
#define CLOVA_PAYLOAD_SPEECH_PLAYERACTIVITY_NAME "playerActivity"
#define CLOVA_PAYLOAD_SPEECH_PLAYERACTIVITY_VALUE_FINISHED "FINISHED"

#endif
