
#ifndef __LGUPLUS_SETTING_H__
#define __LGUPLUS_SETTING_H__

#define WAKEUP_WORD ("WAKEUP_WORD")
#define PING_PERIOD ("PING_PERIOD")
#define AIIF_ENDPOINT ("AIIF_ENDPOINT")
#define INACTIVE_INTERVAL ("INACTIVE_INTERVAL")
#define FIRMWARE_UPDATE ("FIRMWARE_UPDATE")
#define UPLOAD_LOCATION_INFOMATION ("UPLOAD_LOCATION_INFOMATION")
#define SLEEP_MODE ("SLEEP_MODE")

#endif
